name: pr-check

on: pull_request

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest

    env:
      CF_API_TOKEN: ${{secrets.CF_API_TOKEN}}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: modules cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn run lint --quiet

      - name: Build project
        run: yarn run build
